In [3]:
# Import pandas for dataframe operations
import pandas as pd

# Import numpy for numerical operations
import numpy as np

In [ ]:
#Task 1
There are three different tables as given above. Please make three dataframe in python
and save them as three .csv files. From Task 2 to Task 10, use the saved .csv files only.

In [36]:
# Employee DataFrame 

# Creating employee data as dictionary
employee_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],   # Employee IDs
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"],  # Names
    "Gender": ["M", "F", "M", "F", "F"],              # Gender
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"],  # Cities
    "Age": [25, 27, 29, 31, 30]                       # Age
}

# Converting dictionary to DataFrame
employee_df = pd.DataFrame(employee_data)

# Saving employee dataframe to CSV
employee_df.to_csv("Employee.csv", index=False)

In [37]:
#  Seniority DataFrame 

# Creating seniority level data
seniority_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],   # Employee IDs
    "Designation_Level": [2, 2, 3, 2, 3]              # Designation levels
}

# Converting dictionary to DataFrame
seniority_df = pd.DataFrame(seniority_data)

# Saving seniority dataframe to CSV
seniority_df.to_csv("Seniority.csv", index=False)

In [38]:
#  Project DataFrame

# Creating project data (None represents missing cost)
project_data = {
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6",
                "Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Project_Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed",
               "Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
}

# Converting dictionary to DataFrame
project_df = pd.DataFrame(project_data)

# Saving project dataframe to CSV
project_df.to_csv("Project.csv", index=False)

In [ ]:
#Task 2
The cost column in the dataframe “Project” has some missing values. Your task is to
compute these missing values. Replace the missing values by running average. You
should use the “For” loop for this task.

In [39]:
# Reading Project CSV file
project_df = pd.read_csv("Project.csv")

# Initializing sum and count for running average
total = 0
count = 0

# Looping through Project_Cost column
for i in range(len(project_df)):
    
    # Checking if value is not missing
    if not pd.isna(project_df.loc[i, "Project_Cost"]):
        total += project_df.loc[i, "Project_Cost"]  # Add cost
        count += 1                                  # Increase count
    else:
        # Replace missing value with running average
        project_df.loc[i, "Project_Cost"] = total / count

# Display updated project dataframe
project_df

      ID     Project  Project_Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [ ]:
#Task 3
Split the name column in the Employee dataframe into two new columns “First Name”,
and “LastName” and remove the older “name” column.

In [40]:
# Reading Employee CSV
employee_df = pd.read_csv("Employee.csv")

# Splitting Name column into First and Last name
employee_df[["First_Name", "Last_Name"]] = employee_df["Name"].str.split(" ", expand=True)

# Dropping old Name column
employee_df.drop("Name", axis=1, inplace=True)

# Display updated employee dataframe
employee_df

     ID Gender     City  Age First_Name  Last_Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [ ]:
#Task 4
Join all three dataframes in one single dataframe. Name it “Final”

In [41]:
# Reading Seniority CSV
seniority_df = pd.read_csv("Seniority.csv")

# Merging Employee and Seniority dataframes
final_df = pd.merge(employee_df, seniority_df, on="ID")

# Merging result with Project dataframe
final_df = pd.merge(final_df, project_df, on="ID")

# Display Final dataframe
final_df

,ID,Gender,City,Age,First_Name,Last_Name,Designation_Level,Project,Project_Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

In [ ]:
#Task 5
Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project
cost only to employees who have finished the projects.

In [42]:
# Creating Bonus column with 5% bonus for Finished projects
final_df["Bonus"] = np.where(
    final_df["Status"] == "Finished",
    final_df["Project_Cost"] * 0.05,
    0
)

# Display Final dataframe
final_df

,ID,Gender,City,Age,First_Name,Last_Name,Designation_Level,Project,Project_Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [ ]:
#Task 6
Demote the designation level by 1, whose projects have status “fail”. Delete the
employees record whose designation level is above 4.

In [43]:
# Demoting designation level by 1 if project failed
final_df.loc[final_df["Status"] == "Failed", "Designation_Level"] -= 1

# Removing employees whose designation level is above 4
final_df = final_df[final_df["Designation_Level"] <= 4]

# Display Final dataframe
final_df

,ID,Gender,City,Age,First_Name,Last_Name,Designation_Level,Project,Project_Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,1,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,1,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,2,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [ ]:
#Task 7
Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [44]:
# Adding title based on gender
final_df["First_Name"] = np.where(
    final_df["Gender"] == "M",
    "Mr. " + final_df["First_Name"],
    "Mrs. " + final_df["First_Name"]
)

# Dropping Gender column
final_df.drop("Gender", axis=1, inplace=True)

# Display updated dataframe
final_df

,ID,City,Age,First_Name,Last_Name,Designation_Level,Project,Project_Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,1,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [ ]:
#Task 8
Promote designation level by 1 for the employees whose age is more than 29 years using
IF condition.

In [45]:
# Promoting employees whose age is greater than 29
final_df.loc[final_df["Age"] > 29, "Designation_Level"] += 1

# Display updated dataframe
final_df

,ID,City,Age,First_Name,Last_Name,Designation_Level,Project,Project_Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,1,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,4,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,4,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,4,Project 14,2.000000e+05,Finished,10000.0

In [ ]:
#Task 9
Add the cost of all projects for each Employee and save it in new dataframe
“TotalProjCost” with three columns ID, First Name, and Total cost

In [46]:
# Grouping by ID and First Name to calculate total project cost
total_proj_cost = final_df.groupby(
    ["ID", "First_Name"]
)["Project_Cost"].sum().reset_index()

# Renaming column
total_proj_cost.rename(columns={"Project_Cost": "Total_Project_Cost"}, inplace=True)

# Display Total Project Cost dataframe
total_proj_cost

     ID  First_Name  Total_Project_Cost
0  A001    Mr. John        5.063714e+06
1  A002  Mrs. Alice        2.680000e+06
2  A003     Mr. Tom        5.150000e+06
3  A004   Mrs. Nina        9.500000e+06
4  A005    Mrs. Amy        3.850500e+06

In [ ]:
#Task 10
Print all the employee details whose city name contains the letter “o” in it.

In [48]:
# Filtering employees whose city contains letter 'o'
final_df[final_df["City"].str.contains("o", case=False)]

,ID,City,Age,First_Name,Last_Name,Designation_Level,Project,Project_Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 13,3000000.0,Finished,150000.0